### ISSUE TITLE
FR: support mutual exclusive groups

### ISSUE THREAD

**Issue by kunyi731** [openbmc/phosphor-led-manager#8]
Currently I believe asserting a group doesn't actually do anything to other groups. If one has groups corresponding to various mutual exclusive states, e.g.

boot_start:
   // Some LED actions
boot_complete:
   // Some other LED actions

in code one has to explicitly set other groups deasserted first before asserting a group.

This can be simplified by supporting exclusivity in YAML, for example:

boot_start:
   conflict: boot_complete
   // Some LED actions
boot_complete:
   conflict: boot_start
   // Some other LED actions

**Comment by pointbazaar** [comment]
good point, you can support part of that usecase by using "Group Priority" instead of "Led Priority".
Group Priority as a feature was merged recently.

So you can assign priority to an individual group and an asserted group with higher priority overrides one with lower priority.
You can read more about this in the project readme.

Does this cover your use-case?
